lib/imagine_web/router.ex
defmodule ImagineWeb.Router do
  use ImagineWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :fetch_live_flash
    plug :put_root_layout, {ImagineWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug ImagineWeb.Plugs.Auth
  end

  pipeline :manage do
    plug ImagineWeb.Plugs.SetManageRootLayout
    plug ImagineWeb.Plugs.EnsureUser
  end

  pipeline :cms do
    plug :put_layout, {ImagineWeb.LayoutView, :app}
  end

  scope "/manage", ImagineWeb do
    pipe_through [:browser, :manage]

    get "/", CmsController, :index

    get "/cms_pages/:id/edit_content", CmsPageController, :edit_content
    post "/cms_pages/:id/update_content", CmsPageController, :update_content

    post "/cms_pages/:id/set_published_version/:version",
         CmsPageController,
         :set_published_version

    post "/cms_pages/:id/undelete", CmsPageController, :undelete
    delete "/cms_pages/:id/destroy", CmsPageController, :destroy

    resources "/cms_pages", CmsPageController do
      resources "/versions", CmsPageVersionController, as: :version
    end

    resources "/cms_snippets", CmsSnippetController do
      resources "/versions", CmsSnippetVersionController, as: :version
    end

    resources "/cms_templates", CmsTemplateController do
      resources "/versions", CmsTemplateVersionController, as: :version
    end

    get "/account/edit", AccountController, :edit
    post "/account/update", AccountController, :update

    post "/users/:id/disable", UserController, :disable
    post "/users/:id/enable", UserController, :enable
    resources "/users", UserController
  end

  scope "/", ImagineWeb do
    pipe_through [:browser, :manage]

    get "/manage/login", AuthController, :login
    post "/manage/login", AuthController, :handle_login
    delete "/manage/logout", AuthController, :handle_logout
  end

  scope "/", ImagineWeb do
    pipe_through [:browser, :cms]

    get "/*path", CmsRendererController, :show
  end
end

lib/imagine/cms_templates/cms_snippet_version.ex
defmodule Imagine.CmsTemplates.CmsSnippetVersion do
  @moduledoc """
  CmsSnippetVersion - a single version of CmsSnippet
  """

  use Ecto.Schema
  import Ecto.Changeset

  schema "cms_snippet_versions" do
    belongs_to :cms_snippet, Imagine.CmsTemplates.CmsSnippet

    field :version, :integer

    field :name, :string
    field :description, :string
    field :content, :string
    field :content_eex, :string

    timestamps(inserted_at: :created_on, updated_at: :updated_on)
  end

  @doc false
  def changeset(cms_snippet_version, cms_snippet) do
    cms_snippet_version
    |> cast(Map.from_struct(cms_snippet), [
      :name,
      :description,
      :content,
      :content_eex,
      :version
    ])
    |> put_change(:cms_snippet_id, cms_snippet.id)
    |> validate_required([:name, :version, :cms_snippet_id])
  end
end

lib/imagine_web/controllers/cms_snippet_version_controller.ex
defmodule ImagineWeb.CmsSnippetVersionController do
  use ImagineWeb, :controller

  alias Imagine.CmsTemplates
  # alias Imagine.CmsTemplates.CmsSnippetVersion

  def index(conn, params) do
    cms_snippet =
      params["cms_snippet_id"]
      |> CmsTemplates.get_cms_snippet!()
      |> Imagine.Repo.preload([:versions])

    render(conn, "index.html",
      cms_snippet: cms_snippet,
      cms_snippet_versions: cms_snippet.versions
    )
  end

  def show(conn, %{"id" => id} = params) do
    cms_snippet = CmsTemplates.get_cms_snippet!(params["cms_snippet_id"])
    cms_snippet_version = CmsTemplates.get_cms_snippet_version!(id)
    render(conn, "show.html", cms_snippet: cms_snippet, cms_snippet_version: cms_snippet_version)
  end
end

lib/imagine_web/views/cms_snippet_version_view.ex
defmodule ImagineWeb.CmsSnippetVersionView do
  use ImagineWeb, :view
end

lib/imagine_web/templates/cms_snippet_version/index.html.eex
<h1><%= link "Snippets", to: Routes.cms_snippet_path(@conn, :index) %> / <%= link @cms_snippet.name, to: Routes.cms_snippet_path(@conn, :show, @cms_snippet) %> / Versions</h1>

<table class="ui table">
  <thead>
    <tr>
      <th>Version</th>
      <th>Date</th>
    </tr>
  </thead>
  <tbody>
  <%= for cms_snippet_version <- Enum.reverse(@cms_snippet_versions) do %>
    <tr>
      <td><%= link "Version #{cms_snippet_version.version}", to: Routes.cms_snippet_version_path(@conn, :show, @cms_snippet, cms_snippet_version) %></td>
      <td><%= cms_snippet_version.updated_on %></td>
    </tr>
  <% end %>
  </tbody>
</table>

lib/imagine_web/templates/cms_snippet_version/show.html.eex
<h1><%= link "Snippets", to: Routes.cms_snippet_path(@conn, :index) %> / <%= link @cms_snippet.name, to: Routes.cms_snippet_path(@conn, :show, @cms_snippet) %> / <%= link "Versions", to: Routes.cms_snippet_version_path(@conn, :index, @cms_snippet) %> / <%= "Version #{@cms_snippet_version.version}" %></h1>

<table class="ui summary table">
  <tr>
    <td><strong>Name:</strong></td>
    <td><%= link @cms_snippet_version.name, to: Routes.cms_snippet_path(@conn, :show, @cms_snippet) %></td>
  </tr>

  <tr>
    <td><strong>Description:</strong></td>
    <td><%= @cms_snippet_version.description %></td>
  </tr>

  <tr>
    <td><strong>Content:</strong></td>
    <td><%= textarea :f, :content_eex, value: @cms_snippet_version.content_eex %></td>
  </tr>
</table>

<script>
  document.addEventListener('DOMContentLoaded', () => {
    var editor = CodeMirror.fromTextArea(document.getElementById("f_content_eex"), {
      mode: "htmlmixed",
      selectionPointer: true,
      lineNumbers: true,
      viewportMargin: Infinity,
      readOnly: true
    });
  });
</script>