lib/imagine_web/router.ex
defmodule ImagineWeb.Router do
  use ImagineWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :fetch_live_flash
    plug :put_root_layout, {ImagineWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug ImagineWeb.Plugs.Auth
  end

  pipeline :manage do
    plug ImagineWeb.Plugs.SetManageRootLayout
    plug ImagineWeb.Plugs.EnsureUser
  end

  pipeline :cms do
    plug :put_layout, {ImagineWeb.LayoutView, :app}
  end

  scope "/manage", ImagineWeb do
    pipe_through [:browser, :manage]

    get "/", CmsController, :index

    get "/cms_pages/:id/edit_content", CmsPageController, :edit_content
    post "/cms_pages/:id/update_content", CmsPageController, :update_content

    post "/cms_pages/:id/set_published_version/:version",
         CmsPageController,
         :set_published_version

    post "/cms_pages/:id/undelete", CmsPageController, :undelete
    delete "/cms_pages/:id/destroy", CmsPageController, :destroy

    resources "/cms_pages", CmsPageController do
      resources "/versions", CmsPageVersionController, as: :version
    end

    resources "/cms_snippets", CmsSnippetController do
      resources "/versions", CmsSnippetVersionController, as: :version
    end

    resources "/cms_templates", CmsTemplateController do
      resources "/versions", CmsTemplateVersionController, as: :version
    end

    get "/account/edit", AccountController, :edit
    post "/account/update", AccountController, :update

    post "/users/:id/disable", UserController, :disable
    post "/users/:id/enable", UserController, :enable
    resources "/users", UserController
  end

  scope "/", ImagineWeb do
    pipe_through [:browser, :manage]

    get "/manage/login", AuthController, :login
    post "/manage/login", AuthController, :handle_login
    delete "/manage/logout", AuthController, :handle_logout
  end

  scope "/", ImagineWeb do
    pipe_through [:browser, :cms]

    get "/*path", CmsRendererController, :show
  end
end

lib/imagine/cms_pages/cms_page_version.ex
defmodule Imagine.CmsPages.CmsPageVersion do
  @moduledoc """
  CmsPageVersion - a single version of CmsPage
  """

  use Ecto.Schema
  import Ecto.Changeset

  alias Imagine.Accounts.User
  alias Imagine.CmsPages.CmsPage
  alias Imagine.CmsTemplates.CmsTemplate

  @derive {Jason.Encoder,
           only: [
             :version,
             :path,
             :name,
             :title,
             :published_date,
             :article_date,
             :article_end_date,
             :expiration_date,
             :summary,
             :thumbnail_path,
             :feature_image_path,
             :position
           ]}

  schema "cms_page_versions" do
    belongs_to :cms_page, CmsPage

    has_many :versions, through: [:cms_page, :versions]
    has_many :objects, through: [:cms_page, :objects]
    has_many :tags, through: [:cms_page, :tags]

    belongs_to :cms_template, CmsTemplate
    field :cms_template_version, :integer

    belongs_to :parent, CmsPage
    has_many :sub_pages, CmsPage, foreign_key: :parent_id, where: [discarded_at: nil]

    belongs_to :author, User, foreign_key: :updated_by
    field :updated_by_username, :string

    field :version, :integer

    field :path, :string
    field :name, :string
    field :title, :string

    field :layout, :string

    field :published_version, :integer
    field :published_date, :naive_datetime
    field :article_date, :naive_datetime
    field :article_end_date, :naive_datetime
    field :expiration_date, :naive_datetime
    field :expires, :boolean, default: false

    field :summary, :string
    field :html_head, :string
    field :thumbnail_path, :string
    field :feature_image_path, :string

    field :redirect_enabled, :boolean, default: false
    field :redirect_to, :string

    field :position, :integer

    field :comment_count, :integer
    field :search_index, :string

    field :discarded_at, :naive_datetime

    timestamps(inserted_at: :created_on, updated_at: :updated_on)
  end

  @doc false
  def changeset(cms_page_version, %CmsPage{} = cms_page) do
    cms_page_version
    |> cast(Map.from_struct(cms_page), [
      :version,
      :cms_template_id,
      :cms_template_version,
      :parent_id,
      :path,
      :name,
      :title,
      :layout,
      :published_version,
      :published_date,
      :article_date,
      :article_end_date,
      :expiration_date,
      :expires,
      :summary,
      :html_head,
      :thumbnail_path,
      :feature_image_path,
      :redirect_enabled,
      :redirect_to,
      :position,
      :search_index,
      :updated_by,
      :updated_by_username
    ])
    |> put_change(:cms_page_id, cms_page.id)
    |> validate_required([:cms_page_id, :version, :title])
  end
end

lib/imagine_web/controllers/cms_page_version_controller.ex
defmodule ImagineWeb.CmsPageVersionController do
  use ImagineWeb, :controller

  alias Imagine.CmsPages

  def index(conn, params) do
    cms_page =
      params["cms_page_id"]
      |> CmsPages.get_cms_page!()
      |> Imagine.Repo.preload(versions: [:cms_template])

    render(conn, "index.html",
      cms_page: cms_page,
      cms_page_versions: cms_page.versions
    )
  end

  def show(conn, %{"id" => id, "cms_page_id" => cms_page_id}) do
    cms_page = CmsPages.get_cms_page!(cms_page_id)

    cms_page_version =
      CmsPages.get_cms_page_version!(id)
      |> Imagine.Repo.preload([:cms_template, :parent, :author])

    render(conn, "show.html", cms_page: cms_page, cms_page_version: cms_page_version)
  end

  def delete(conn, %{"id" => id, "cms_page_id" => cms_page_id}) do
    cms_page = CmsPages.get_cms_page!(cms_page_id)
    cms_page_version = CmsPages.get_cms_page_version!(id)

    unless cms_page.version == cms_page_version.version ||
             cms_page.published_version == cms_page_version.version do
      {:ok, cms_page_version} = CmsPages.delete_cms_page_version(cms_page_version)

      conn
      |> put_flash(:info, "Version #{cms_page_version.version} deleted successfully.")
      |> redirect(to: Routes.cms_page_path(conn, :show, cms_page))
    end
  end
end

lib/imagine_web/views/cms_page_version_view.ex
defmodule ImagineWeb.CmsPageVersionView do
  use ImagineWeb, :view
end

lib/imagine_web/templates/cms_page_version/index.html.eex
<h1><%= link "Pages", to: Routes.cms_page_path(@conn, :index) %> / <%= link @cms_page.path, to: Routes.cms_page_path(@conn, :show, @cms_page) %> / Versions</h1>

<table class="ui table">
  <thead>
    <tr>
      <th>Version</th>
      <th>Title</th>
      <th>Template</th>
      <th>Published date</th>
      <th>Author</th>
    </tr>
  </thead>
  <tbody>
    <%= for cms_page_version <- Enum.reverse(@cms_page_versions) do %>
    <tr>
      <td><%= link "Version #{cms_page_version.version}", to: Routes.cms_page_version_path(@conn, :show, @cms_page, cms_page_version) %></td>
      <td><%= cms_page_version.title %></td>
      <td><%= link cms_page_version.cms_template.name, to: Routes.cms_template_version_path(@conn, :show, cms_page_version.cms_template_id, cms_page_version.cms_template_version) %></td>
      <td><%= cms_page_version.published_date %></td>
      <td><%= link cms_page_version.updated_by_username, to: Routes.user_path(@conn, :show, cms_page_version.updated_by) %></td>
    </tr>
    <% end %>
  </tbody>
</table>

lib/imagine_web/templates/cms_page_version/show.html.eex
<h1><%= link "Pages", to: Routes.cms_page_path(@conn, :index) %> / <%= link @cms_page.path, to: Routes.cms_page_path(@conn, :show, @cms_page) %> / <%= link "Versions", to: Routes.cms_page_version_path(@conn, :index, @cms_page) %> / <%= "Version #{@cms_page_version.version}" %></h1>

<div class="button-bar">
  <%= link raw(~s(<i class="pencil alternate icon"></i> Edit)), to: "/#{@cms_page.path}/version/#{@cms_page_version.version}/edit", class: "ui icon labeled button" %>
  <%= link raw(~s(<i class="desktop icon"></i> Preview)), to: "/#{@cms_page.path}/version/#{@cms_page_version.version}", class: "ui icon labeled button" %>
  <%= if @cms_page.version == @cms_page_version.version || @cms_page.published_version == @cms_page_version.version do %>
    <%= link raw(~s(<i class="trash alternate outline icon"></i> Delete)), to: "#", title: "This version is in use and cannot be deleted.", class: "ui icon labeled disabled basic button" %>
  <% else %>
    <%= link raw(~s(<i class="trash alternate outline icon"></i> Delete)), to: Routes.cms_page_version_path(@conn, :delete, @cms_page, @cms_page_version), method: :delete, data: [confirm: "Are you sure you want to delete this version? There is no undo."], class: "ui icon labeled negative basic button" %>
  <% end %>
</div>

<table class="ui summary table">
  <tr>
    <td><strong>Author:</strong></td>
    <td><%= link "#{Imagine.Accounts.User.name(@cms_page_version.author)}  (#{@cms_page_version.updated_by_username})", to: Routes.user_path(@conn, :show, @cms_page_version.author) %></td>
  </tr>

  <tr>
    <td><strong>Template:</strong></td>
    <td><%= @cms_page_version.cms_template.name %></td>
  </tr>

  <tr>
    <td><strong>Parent:</strong></td>
    <td><%= link @cms_page_version.parent.name, to: Routes.cms_page_path(@conn, :show, @cms_page_version.parent) %></td>
  </tr>

  <tr>
    <td><strong>Path:</strong></td>
    <td><%= @cms_page_version.path %></td>
  </tr>

  <tr>
    <td><strong>Title:</strong></td>
    <td><%= @cms_page_version.title %></td>
  </tr>

  <tr>
    <td><strong>Article date:</strong></td>
    <td><%= @cms_page_version.article_date %></td>
  </tr>

  <tr>
    <td><strong>Article end date:</strong></td>
    <td><%= @cms_page_version.article_end_date %></td>
  </tr>

  <tr>
    <td><strong>Published date:</strong></td>
    <td><%= @cms_page_version.published_date %></td>
  </tr>

  <tr>
    <td><strong>Expires:</strong></td>
    <td>
      <%= if @cms_page_version.expires do %>
        Yes - <%= @cms_page_version.expiration_date %>
      <% else %>
        No
      <% end %>
    </td>
  </tr>

  <tr>
    <td><strong>Summary:</strong></td>
    <td><%= @cms_page_version.summary %></td>
  </tr>

  <tr>
    <td><strong>HTML head:</strong></td>
    <td><%= @cms_page_version.html_head %></td>
  </tr>

  <tr>
    <td><strong>Thumbnail:</strong></td>
    <td><%= link Path.basename(@cms_page_version.thumbnail_path || "") |> String.replace(~r/\?\d+$/, ""), to: @cms_page_version.thumbnail_path || "" %></td>
  </tr>

  <tr>
    <td><strong>Feature image:</strong></td>
    <td><%= link Path.basename(@cms_page_version.feature_image_path || "") |> String.replace(~r/\?\d+$/, ""), to: @cms_page_version.feature_image_path || "" %></td>
  </tr>

  <tr>
    <td><strong>Redirects to:</strong></td>
    <td><%= if @cms_page_version.redirect_enabled, do: @cms_page_version.redirect_to %></td>
  </tr>

  <tr>
    <td><strong>Position:</strong></td>
    <td><%= @cms_page_version.position %></td>
  </tr>
</table>