lib/imagine_web/router.ex
defmodule ImagineWeb.Router do
  use ImagineWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :fetch_live_flash
    plug :put_root_layout, {ImagineWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug ImagineWeb.Plugs.Auth
  end

  pipeline :manage do
    plug ImagineWeb.Plugs.SetManageRootLayout
    plug ImagineWeb.Plugs.EnsureUser
  end

  pipeline :cms do
    plug :put_layout, {ImagineWeb.LayoutView, :app}
  end

  scope "/manage", ImagineWeb do
    pipe_through [:browser, :manage]

    get "/", CmsController, :index

    get "/cms_pages/:id/edit_content", CmsPageController, :edit_content
    post "/cms_pages/:id/update_content", CmsPageController, :update_content

    post "/cms_pages/:id/set_published_version/:version",
         CmsPageController,
         :set_published_version

    post "/cms_pages/:id/undelete", CmsPageController, :undelete
    delete "/cms_pages/:id/destroy", CmsPageController, :destroy

    resources "/cms_pages", CmsPageController do
      resources "/versions", CmsPageVersionController, as: :version
    end

    resources "/cms_snippets", CmsSnippetController do
      resources "/versions", CmsSnippetVersionController, as: :version
    end

    resources "/cms_templates", CmsTemplateController do
      resources "/versions", CmsTemplateVersionController, as: :version
    end

    get "/account/edit", AccountController, :edit
    post "/account/update", AccountController, :update

    post "/users/:id/disable", UserController, :disable
    post "/users/:id/enable", UserController, :enable
    resources "/users", UserController
  end

  scope "/", ImagineWeb do
    pipe_through [:browser, :manage]

    get "/manage/login", AuthController, :login
    post "/manage/login", AuthController, :handle_login
    delete "/manage/logout", AuthController, :handle_logout
  end

  scope "/", ImagineWeb do
    pipe_through [:browser, :cms]

    get "/*path", CmsRendererController, :show
  end
end

lib/imagine_web/views/layout_view.ex
defmodule ImagineWeb.LayoutView do
  use ImagineWeb, :view
end

lib/imagine_web/templates/layout/app.html.eex
<main id="content-container" role="main" class="ui container">
  <%# error messages are persistent %>
  <%= if err = get_flash(@conn, :error) do %>
    <p class="ui warning message" role="alert"><%= err %></p>
  <% end %>

  <%# simple information messages are not %>
  <%= if info = get_flash(@conn, :notice) || get_flash(@conn, :info) do %>
  <script>
    document.addEventListener('DOMContentLoaded', () => {
      $('body').toast({ message: "<%= Phoenix.HTML.javascript_escape info %>", class: 'black', displayTime: 7000 });
    });
  </script>
  <% end %>

  <%= @inner_content %>
</main>

lib/imagine_web/templates/layout/live.html.heex
<main id="content-container" role="main" class="ui container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/imagine_web/templates/layout/live.html.leex
<main id="content-container" role="main" class="ui container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/imagine_web/templates/layout/manage.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>

    <title><%= assigns[:page_title] && "#{assigns[:page_title]} < " %>Manage &lt; Imagine CMS</title>

    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/assets/css/manage.css") %>"/>
    <script src="<%= Routes.static_path(@conn, "/assets/js/manage.js") %>" defer></script>
  </head>

  <body id="imagine-app" class="semantic-ui">
    <nav role="navigation" class="ui stackable inverted fixed main menu mobile hidden">
      <%= link "Imagine CMS", to: "/manage", class: "header item" %>

      <%= if assigns[:current_user] do %>
        <%= link "Pages", to: Routes.cms_page_path(@conn, :index), class: "item" %>
        <%= link "Templates", to: Routes.cms_template_path(@conn, :index), class: "item" %>
        <%= link "Snippets", to: Routes.cms_snippet_path(@conn, :index), class: "item" %>
        <%= link "Users", to: Routes.user_path(@conn, :index), class: "item" %>
      <% end %>

      <div class="right menu">
        <%= if current_user = assigns[:current_user] do %>
          <a href="" class="item hw_changelog">Updates</a>
          <a href="/" class="item">View Site</a>

          <div class="ui simple dropdown item">
            <%= Imagine.Accounts.User.name(current_user) %>
            <i class="dropdown icon"></i>
            <div class="ui menu">
              <%= link "Account", to: Routes.account_path(@conn, :edit), class: "item" %>
              <%= link "Log out", to: Routes.auth_path(@conn, :handle_logout), method: :delete, class: "item" %>
            </div>
          </div>
        <% else %>
          <a href="/" class="item">View Site</a>
          <%= link "Log in", to: Routes.auth_path(@conn, :login), class: "item" %>
        <% end %>
      </div>
    </nav>

    <!-- mobile menu -->
    <div id="mobile-menu" class="slideout-menu slideout-menu-left">
      <div class="ui inverted vertical menu">
        <%= link "Imagine CMS", to: "/manage", class: "item" %>
        <div class="item"></div>
        <%= if assigns[:current_user] do %>
          <%= link "Pages", to: Routes.cms_page_path(@conn, :index), class: "item" %>
          <%= link "Templates", to: Routes.cms_template_path(@conn, :index), class: "item" %>
          <%= link "Snippets", to: Routes.cms_snippet_path(@conn, :index), class: "item" %>
          <%= link "Users", to: Routes.user_path(@conn, :index), class: "item" %>
          <div class="item"></div>
          <a href="" class="item hw_changelog">Updates</a>
          <a href="/" class="item">View Site</a>
          <div class="item"></div>
          <%= link "Account", to: Routes.account_path(@conn, :edit), class: "item" %>
          <%= link "Log out", to: Routes.auth_path(@conn, :handle_logout), method: :delete, class: "item" %>
        <% else %>
          <a href="/" class="item">View Site</a>
          <%= link "Log in", to: Routes.auth_path(@conn, :login), class: "item" %>
        <% end %>
      </div>
    </div>
    <div id="panel" class="panel slideout-panel slideout-panel-left">
      <div class="ui mobile only">
  			<div class="ui inverted menu">
  				<a class="item mobile-menu-toggle"><i class="bars icon"></i></a>
  			</div>
      </div>
      <div class="mobile hidden" style="height: 40px;"></div>

      <%= @inner_content %>

      <footer class="ui inverted segment">
        <div id="build-info" class="ui container">
          Imagine <%= Imagine.Config.version() %>
          (<%= Imagine.Config.build_number() %>) &ndash;
          <%= Timex.format! Imagine.Config.release_built_at(), "{Mfull} {D}, {YYYY}" %>
        </div>
      </footer>
    </div>
  </body>
</html>